# Generated by Django 4.2.7 on 2024-02-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(default=2, max_length=24),
            preserve_default=False,
        ),
    ]
